#!/bin/bash
echo -e "Content-type: text/plain\n"
query=$(echo $QUERY_STRING | grep '[0-9]*-[0-9]*' -o)
get-date(){ date --date=@$(echo $query | cut -d "-" -f $1) +%y%m%d%H%M%S; }
list=$(curl http://10.129.8.248/tf1/tf1.m3u8|grep .ts|sed 's/.ts//')
cat << endline
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-TARGETDURATION:10
#EXT-X-MEDIA-SEQUENCE:0
#EXT-X-PLAYLIST-TYPE:VOD
endline
debut=$(get-date 1) ;fin=$(get-date 2)
for i in $list; do
    if [[ $i < $fin ]] ;then if [[ $debut < $i ]]; then
            echo \#EXTINF:10.000000,-1 tvg-id="1",CatchUpTV
            echo http://10.129.8.248/tf1/$i.ts
     fi;else
        echo break
     fi
done
echo \#EXT-X-ENDLIST
